# Generated by Django 4.2.5 on 2023-09-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вида')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вид растения',
                'verbose_name_plural': 'Виды растений',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота (м)')),
                ('health_condition', models.CharField(choices=[('Healthy', 'Здоровое'), ('Diseased', 'Болеет'), ('Pest Infested', 'Поражено вредителями'), ('Nutrient Deficient', 'Недостаток питательных веществ'), ('Wilting', 'Увядание'), ('Dehydrated', 'Обезвоживание'), ('Frost Damage', 'Повреждение от мороза'), ('Sunburn', 'Солнечные ожоги'), ('Injured', 'Травмированное'), ('Other', 'Другое')], default='Healthy', max_length=30, verbose_name='Состояние здоровья')),
                ('crown_length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина кроны (м)')),
                ('water_access', models.BooleanField()),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('planting_date', models.DateField()),
                ('full_growth_photo', models.ImageField(help_text='Добавьте фотографию растения в полный рост.', upload_to='tree_photos/full_growth/', verbose_name='Фотография в полный рост')),
                ('fetal_photo', models.ImageField(help_text='Добавьте фотографию листьев или плодов растения.', upload_to='tree_photos/fetal_photo/', verbose_name='Фотография листьев/плодов')),
                ('reference_point_photo', models.ImageField(help_text='Добавьте фотографию, которая поможет определить местоположение растения.', upload_to='tree_photos/reference_point/', verbose_name='Фотография реперной точки')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.species', verbose_name='Вид растения')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
    ]
