# Generated by Django 4.2.5 on 2023-09-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_plant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='water_access',
            field=models.CharField(choices=[('Yes', 'Да, регулярно поливается'), ('No', 'Нет, не поливается'), ('Unknown', 'Неизвестно'), ('Seasonal', 'Поливается сезонно'), ('Limited', 'Ограниченный доступ к воде'), ('Abundant', 'Изобильный доступ к воде'), ('Artificial', 'Искусственное обеспечение водой'), ('Natural Springs', 'Источники воды'), ('Rainwater Collection', 'Сбор дождевой воды'), ('Irrigation System', 'Используется система орошения'), ('Other', 'Другое')], max_length=30, verbose_name='Доступ к воде'),
        ),
    ]
